### ISSUE TITLE
[Feat] 특정 유저의 업적 목록 가져오는 API 추가 요청드립니다.

### ISSUE THREAD

**Issue by PennyBlack2008** [404-DriverNotFound/backend-b#100]
## 기능에 대한 설명
특정 유저의 **업적** 목록을 가져오는 API 추가 요청드립니다. GET /achievements/{name} 이면 좋을 것 같습니다. 이 API가 완성되면 상대방의 ProfilePage에서 해당 유저의 **업적**을 확인할 수 있습니다.

현재 GET /achievements API로 나의 **업적** 목록을 조회해서 ProfilePage에서 보여주고 있습니다. 그런데, 다른 사람의 Profile의 **업적**을 확인할 수 없습니다. 요청 드린 API가 추가되면 정상적으로 다른 사람의 **업적**을 확인할 수 있을 것같습니다.

## 구현 상세 (Optional)
- [ ] 상대방의 **업적**을 확인할 수 있는 GET /achievements/{name} API를 추가한다.

## REFERENCE (Optional)
.

**Comment by ykoh42** [comment]
#104 API를 `GET` `/users/:name/achievements` 로 설계한 버전입니다.

**Comment by ykoh42** [comment]
매치 또한 `GET` `/users/:name/matches` 같은 스타일의 설계가 적합해보입니다.
