### ISSUE TITLE
[Feat] 42 로그인 완료 시 redirect 경로를 case에 따라 다르게 설정

### ISSUE THREAD

**Issue by hyo-choi** [404-DriverNotFound/backend-b#36]
## 기능에 대한 설명
- 현재는 42 로그인 완료 시 무조건 프론트엔드의 `/`로 리디렉션 하고 있습니다.
- 그런데 프론트엔드에서 API에 요청-응답한 후 보여줄 페이지를 판별하는 식으로 구현하니 로직이 꼬여서, 백엔드에서 리디렉션 분기가 나뉘는 편이 좋을 것 같습니다.
- 로그인 상황에서
  1. 회원가입이 필요한 경우(DB에 등록되어있지 않은 유저) -> `/register`로 리디렉션
  2. 가입된 유저이고 2FA 인증을 활성화시킨 경우 -> `/2FA`로 리디렉션
  3. 가입된 유저이고 2FA 인증이 비활성화된 경우 -> `/`로 리디렉션  

이렇게 분기가 나뉘면 로직이 꼬이지 않을 것 같습니다. 확인 부탁드립니다!

**Comment by ykoh42** [comment]
- 위에 언급해주신 상황에서 아래와 같이 처리하도록 하겠습니다.
  1. `http://localhost:3000/register`
  2. `http://localhost:3000/2fa` -> 대문자가 아니고 소문자로 하였는데, 대문자를 사용하는 경우를 잘 못봐서 소문자로 했는데 대문자가 맞는것같으시면 대문자로 수정토록할게요
  3. `http://localhost:3000` -> 처음에 말씀해주는거에서 `/` 요거 차이입니다!

**Comment by hyo-choi** [comment]
부가적인 문제 없이 잘 해결되었습니다! URL 수정도 안 해주셔도 될 것 같습니다. 감사합니다 :)
저희 레포가 아니라 임의로 close하면 안 될 것 같아서 그냥 뒀으니 원하시는 타이밍에 close 해주세요! 😄
