### ISSUE TITLE
[Feat] GET /users/{name} API 구현 요청드립니다.

### ISSUE THREAD

**Issue by hyo-choi** [404-DriverNotFound/backend-b#55]
## 기능에 대한 설명
현재 프론트엔드에서는 `http://localhost:3000/propfile/:id`로 접속하면 -> 페이지 내부에서 React router를 이용해 URL의 id 정보를 받아오고 -> API 서버에 `GET /users/{uuid}` 요청을 보내 사용자의 정보를 받아오고 있습니다.
그런데 /profile 뒤에 /uuid가 붙는 형태의 URL이 유저 입장에서는 의아하게 느껴질 수 있을 것 같고, 일반적으로는 이런 상황에서 `/profile/:name` 형태의 URL을 사용할 것 같습니다. 그래서 프론트엔드 팀에서는 프로필 페이지의 URL 형태를 `/profile/:name`으로 개선하고자 합니다.

프론트엔드 로직 상 `/profile/:name`으로 접속하여 `GET /users/{uuid}`로 요청을 보내려면
1. 전체 유저 목록을 먼저 요청
2. 응답에서 name이 일치하는 유저를 필터링하고
3. 필터링해 얻은 id를 가지고 다시 `GET /users/{uuid}`로 요청

위와 같은 과정을 거쳐야 하는데, `GET /users/{name}` API만 있으면 이런 비효율적인 방식을 사용하지 않아도 될 것 같아 새로 API 구현을 요청드려봅니다.

- **결론**: `GET /users/{name}` API 구현을 요청드립니다. 이 API가 구현되면 `GET /users/{uuid}`는 없어도 무방할 것 같습니다.

## 구현 상세 (Optional)
x

## REFERENCE (Optional)
x

**Comment by ykoh42** [comment]
PR(#56) 올렸습니다.
