### ISSUE TITLE
[Fix] /friendship API 구조 수정 요청드립니다.

### ISSUE THREAD

**Issue by hyo-choi** [404-DriverNotFound/backend-b#57]
## 문제점
프론트엔드 팀에서는 현재 profile 페이지 작업 중에 있습니다. 해당 유저가 친구인지/차단된 유저인지 여부에 따라 화면을 다르게 렌더링해주려 했는데, 그러던 중 현재 구현되어있는 API를 그대로 이용하려면 모든 친구 관련 기능 구현이 난해해지고 이를 위해 지나치게 많은 API 요청을 보내야 할 것 같다고 판단했습니다. 그래서 전반적인 구조 수정을 요청드리고 싶은데 이슈 확인해주신 후 대화를 나눠보면 좋을 것 같습니다.

### 현재 상황
- 프론트엔드 팀이 구현하고자 한 기능
  특정 유저가 사용자의 친구인지 확인하고 이에 따라 화면을 다르게 렌더링
- 현재 API를 사용한다면
  1. `GET /friendship`으로 모든 **관계 id**를 획득
  2. 1에서 얻은 id를 이용해 `GET /friendship/{uuid}`로 **모든** 관계에 요청을 보내며 해당 유저와의 관계가 존재하는지 확인

필요한 정보는 간단한 데 비해 2번 과정에서 지나치게 많은 요청/응답이 일어나야만 하는 상황입니다.

### API가 수정되지 않을 시 우려되는 상황
이후 친구 목록을 구현할 때에도 위처럼 **모든 관계**에 대해 요청을 보내서 리스트를 구현해야 합니다.

## 예상되는(제대로 된) 동작
프로필 페이지, 친구 목록 페이지 등은 사용자가 빈번하게 접근하는 주요 페이지이기 때문에 API가 지금처럼 구현되어 있으면 UX의 질도 낮아지고 API 서버에도 부하가 걸리기 쉬울 것이라 생각합니다. 응답이 이런 형태로 오면 좋을 것 같은데 수정 가능한 부분일까요?
- `GET /friendship`
```
[
  {
    requester: string, // 닉네임
    addressee: string, // 닉네임
    updatedAt: string, // Date
    status: 'PENDING' | 'ACCEPT' | 'DECLINE',
  },
 ...
]
```
- `GET /friendship/{name}`
```
{
  requester: string, // 닉네임
  addressee: string, // 닉네임
  updatedAt: string, // Date
  status: 'PENDING' | 'ACCEPT' | 'DECLINE',
}
```

## 해결 방법 (optional)
x

## 버그 재현 방법 (버그를 발생시키는 방법)
- 버그가 아니므로 따로 작성하지 않겠습니다.

**Comment by ykoh42** [comment]
## 프로필 렌더링
> 프론트엔드 팀에서는 현재 profile 페이지 작업 중에 있습니다. 해당 유저가 친구인지/차단된 유저인지 여부에 따라 화면을 다르게 렌더링해주려 했는데..

프로필 화면에서 다르게 랜더링하는 부분이
친구일경우는 프로필을 조회할수 있고 친구가 아니면 프로필을 조회할수 없고
이런느낌의 렌더링인가요?

## 예상되는(제대로 된) 동작의 두번째 꼭지 부분
> `GET` `/friendships/{name}`

이 부분은 내용 파악이 제대로 안되는 부분이 있어요.
우선 friendship은 `name`으로 식별할 수 없어서 지금은 `uuid`로 식별하도록 되어있습니다.

의도하신 부분이 특정유저가 가지고 있는 친구관계들에 대해서 모두 가져오는 API를 의도하고 말씀하신건가요?

이거와 관련된 내용으로..
지금 현재 나와 관련있는 친구관계가 아니면 가져오지 않게 의도적으로 구현되어 있는데 이 부분도 혹시 수정이 필요할까요?

## 예상되는(제대로 된) 동작의 첫번째 꼭지 부분
> `GET` `/friendships`

이 부분은 의도하시는 바가 어떤 내용인지 알것같아요.
결국 필요한건 `친구목록` `차단목록` `대기목록` 처럼 유저들의 목록이 필요한데, 추가적인 요청이 필요하다는 이야기인것으로 이해됩니다!
근데 또 어떤 친구관계의 상태를 바꾼다고 생각했을때, 친구관계의 id가 필요하긴 할것이거든요. 그래서 이것도 조금 고민해봐야될 부분인것같아요.


친구 부분이 확실히 픽스된게 없어서 된다 안된다 딱 말씀드리기 애매한 부분이 있습니다.. 조금더 고민해보도록할게용

**Comment by hyo-choi** [comment]
## 프로필 렌더링
프로필 렌더링의 경우 아래처럼 친구 여부에 따라 버튼을 다르게 보여주는 것을 의도하고 말씀드렸습니다!
- 친구가 아닌 경우
![image](https://user-images.githubusercontent.com/57004991/128985162-bf137b96-de4d-44f9-9bb4-bac7828f6a50.png)
- 친구인 경우
![image](https://user-images.githubusercontent.com/57004991/128985191-864b10f9-bbed-47c8-803f-219825a590a7.png)

## 예상되는(제대로 된) 동작의 두번째 꼭지 부분

> 이 부분은 내용 파악이 제대로 안되는 부분이 있어요.
우선 friendship은 name으로 식별할 수 없어서 지금은 uuid로 식별하도록 되어있습니다.
>
> 의도하신 부분이 특정유저가 가지고 있는 친구관계들에 대해서 모두 가져오는 API를 의도하고 말씀해주셨을까요?

이 부분은 **현재 사용자와 {name}의 친구 상태를 돌려주는 API**를 의도하고 말씀드린 것인데 설명이 모자랐던 것 같습니다. 그런데 제일 처음에 제안드린 `GET /friendship` API처럼 구현이 변경된다면 이 API가 반드시 필요하지는 않을 것 같아요. 있으면 좋고 없어도 괜찮을 듯한 부분이라 구현해주셔도 좋고 안 해주셔도 괜찮습니다!

> 지금 현재 나와 관련있는 친구관계가 아니면 가져오지 않게 의도적으로 구현되어 있는데 이 부분도 혹시 수정이 필요할까요?

이 부분은 나와 관련있는 친구관계가 아니면 알 필요가 없을 것 같아 수정하지 않으셔도 될 것 같습니다!

## 예상되는(제대로 된) 동작의 첫번째 꼭지 부분
> 근데 또 어떤 친구관계의 상태를 바꾼다고 생각했을때, 친구관계의 id가 필요하긴 할것이거든요. 그래서 이것도 조금 고민해봐야될 부분인것같아요.

이 부분을 생각해보지 못하고 응답 형태를 제안드렸네요...! 그러면 응답을 이렇게 주시는 건 어떨까요?
- `GET /friendship`
```
[
  {
    id: string, // 관계 테이블의 uuid <- 추가했습니다!
    requester: string, // 닉네임
    addressee: string, // 닉네임
    updatedAt: string, // Date
    status: 'PENDING' | 'ACCEPT' | 'DECLINE',
  },
 ...
]
```

id를 함께 받으면 관계 수정에도 사용할 수 있을 것 같습니다.

---

일단 프론트엔드 팀은 friendship API가 fix될 때까지 관련 기능 구현은 보류해두고 다른 작업부터 하고 있겠습니다. 한 번 고민해보시고 fix되면 다시 말씀해주시면 될 것 같아요. 감사합니다! 👍

**Comment by hyo-choi** [comment]
프론트엔드 팀에서 API 설계에 관한 회의를 진행하였습니다.
해당 내용은 스크럼 미팅 시간에 백엔드 팀과 공유하였으나 코멘트도 추가로 남겨둡니다!
- [회의록 링크](https://twisty-broccoli-136.notion.site/API-8e15a10c99474617b877e7da880978c4)
