### ISSUE TITLE
[Fix] 2FA 변경 버그(나의 정보 수정하기API)

### ISSUE THREAD

**Issue by PennyBlack2008** [404-DriverNotFound/backend-b#58]
## 문제 버전 환경
ft_Transcendence-b(master) : 8월 11일 수요일 기준 (merged Feat: redis 컨테이너 추가(#13) (#15))
backend-b(feat/Friendship#33)
frontend-b(feat/Page-Profile#47)

## 문제점
나의 정보 수정하기 API로 해당 user의 `enable2FA` 상태를 **true**에서 **false**로 수정할 수 없음.

## 예상되는(제대로 된) 동작
나의 정보 수정하기 API로 user의 `"enable2FA": true` 상태를 **false**로 요청(request)하면,
응답(response)에 `"enable2FA": false` 가 담겨서 온다.

## 해결 방법 (optional)
현재 user의 `enable2FA`가 **false**에서 **true**로 바뀔 수 있고, **false**에서 **false**로 요청하면 **false**로 응답받습니다. 
**true**에서 **false**만 문제가 되는 것이라서 여기서 힌트를 얻으실 수 있으셨으면 좋겠습니다.

## 버그 재현 방법 (버그를 발생시키는 방법)
단계 별로 기술해주세요.
1. 해당 문제환경을 재구성한다.
2. swagger로 로그인을 한다.
3. `enable2FA:false` 유저를 생성한다.
4. 나의 정보 수정하기 API로 `enable2FA:true`로 변경한다.
5. 다시 `enable2FA:false`로 변경해본다.
6. 응답에서 `enable2FA:false`로 바뀌었는 지 확인하고 바뀌지 않았다면 본 이슈와 동일합니다.

## 참고 이미지
<img width="621" alt="스크린샷 2021-08-11 오후 10 33 04" src="https://user-images.githubusercontent.com/59194905/129046450-5aef627d-3512-48e1-a824-0493ac759337.png">

**Comment by ykoh42** [comment]
#59 에서 픽스했습니당!
