### ISSUE TITLE
[Feat] 2FA를 활성화 상태로 변경한 유저가 로그인 할 때의 redirection 추가

### ISSUE THREAD

**Issue by hyo-choi** [404-DriverNotFound/backend-b#61]
## 기능에 대한 설명
**2FA를 비활성화 -> 활성화 상태로 변경한 경우** 백엔드 로직 상 해당 세션동안은 2FA 여부를 따지지 않고, 다음 세션부터 2FA 인증 여부에 따라 API 요청의 유효성을 확인하는 것으로 알고 있습니다.
이번에 프론트엔드에서 유저 정보 수정 기능을 구현함에 따라 유저가 직접 본인의 2FA 활성화 여부를 변경할 수 있게 되었고, 이에 따라 다시 로그인할 때 QR코드를 등록하는 절차가 필요해졌습니다. 프론트엔드에서는 QR코드 발급 여부를 확인할 수 없기 때문에 백엔드에서 로그인 시 **DB에 존재하는+2FA를 활성화한+QR코드를 발급받지 않은 유저**를 `/register/2fa`로 redirection 시켜주시면 프론트엔드에서 받아 처리할 수 있을 것 같습니다. 확인 부탁드리겠습니다! 😄

## 구현 상세 (Optional)
x

## REFERENCE (Optional)
x

**Comment by ykoh42** [comment]
_#51 이슈랑도 관련이 있는 부분 같은데, 

혹시 이미 QR이 발급되어 있으면

새로 발급되지 못하게 403에러를 보내주는 형태로 하면

리디렉션 없이 해결할 수 있을까요?

위의 방법으로 해결되지 않는다면 리디렉션 하는 부분을 추가해보도록 할게요!

**Comment by hyo-choi** [comment]
지금 프론트엔드 팀에서 백엔드 팀과 상의해야 할 만한 부분을 몇 군데 찾아서, 말씀해주신 부분에 답변 드리기 전에 해당 부분부터 먼저 설명드려야 할 것 같아요. 그리고 현재 상황이 여러 문제가 복합적으로 얽혀 있어서 하나의 문제에 대해서만 이야기하기 어렵습니다. 전부 읽어주시고 설명이 모자라다 느끼시는 부분이 있으면 디스코드 등에서 다시 이야기 나눠봐도 좋을 것 같습니다.

## 상의할 점
### 2fa를 비활성화 했을 때 `authenticatorSecret`을 폐기해야 하는지
`PATCH /users/me`로 요청을 보내 `enable2FA`를 변경해도 `authenticatorSecret`이 변경되지 않는 것을 확인했습니다. 저희는 2FA를 비활성화 시키면 `authenticatorSecret`이 폐기되고, 2FA를 활성화시키면 새로운 QR코드를 등록해야 하는 것이 아닌가 생각했는데, 일반적으로 2FA를 (1) 활성화 -> (2) 비활성화 -> (3) 활성화 하면 (1)에서 발급받은 QR코드의 `authenticatorSecret`을 (3)에서도 그대로 사용할까요?

### 유저가 `/register/2fa`에서 새로고침할 가능성에 대해
유저 입장에서는 QR 코드를 등록할 때 새로고침을 할 수도 있고, 다른 네트워크상의 이유로 페이지를 다시 로딩하게 될 수도 있을 것 같습니다. 프론트엔드 팀에서는 UX를 고려했을 때 여러 번 발급받는 동작을 막지 않는 것이 더 자연스럽다고 생각하고 있습니다. QR 코드를 여러 번 발급받았더라도 마지막으로 등록한 QR코드가 valid하다고 간주하면 #51 을 해결하지 않아도 될 것 같아요.

## 말씀해주신 부분
> #51 이슈랑도 관련이 있는 부분 같은데,

일단 저희가 요청드린 부분은 #51 이슈와 연관이 없어 보입니다. 저희가 의도한 상황은 QR 코드를 단 한 번도 등록한 적 없는 유저가 2FA를 처음으로 활성화 시켰을 때 QR 코드를 등록하는 화면으로 이동해야 하는 상황입니다. 말씀하신 부분은 기존에 QR코드를 등록한 적 있는 유저가 QR코드를 재발급받으려 하는 상황인데 저희 요청과는 관련이 없는 것 같아요. #51 은 위의 **새로고침할 가능성** 항목과 연관해서 생각해주시면 좋겠습니다.

## 프론트엔드에서 (현재)생각중인 진행 방향
- `PATCH /users/me`에 요청했을 때 `enable2FA`가 `false`로 변경되면 `authenticatorSecret`을 폐기한다.
- `enable2FA`가 true+`authenticatorSecret`이 없는 유저가 로그인하면 `/register/2fa`로 redirection한다.
- `GET /auth/otp/qrcode`로 요청이 오면 매번 새로운 QR 코드를 발급해준다. (현재 동작 그대로)

감사합니다!

**Comment by ykoh42** [comment]
- `PATCH` `/users/me`에 요청했을 때 `enable2FA`가 `false`로 변경되면 `authenticatorSecret`을 폐기한다.
    - 폐기하는게 올바른 동작이 맞는 것같습니다. 폐기하는 쪽으로 수정하도록 할게요
    
- enable2FA가 true+authenticatorSecret이 없는 유저가 로그인하면 /register/2fa로 redirection한다.
    - 이것도 리디렉션 하는 쪽으로 수정할게요!

- GET /auth/otp/qrcode로 요청이 오면 매번 새로운 QR 코드를 발급해준다. (현재 동작 그대로)
    - 이건 저는 매번 새로 발급되면 안된다고 생각하는데, 우선 그대로 냅두도록 할게요!

**Comment by hyo-choi** [comment]
확인했습니다!

> - GET /auth/otp/qrcode로 요청이 오면 매번 새로운 QR 코드를 발급해준다. (현재 동작 그대로)
>   - 이건 저는 매번 새로 발급되면 안된다고 생각하는데, 우선 그대로 냅두도록 할게요!

이 부분은 회의 시간에 한 번 논의해봐도 좋을 것 같아요. 일단 작업 잘 부탁드립니다! 😄

**Comment by ykoh42** [comment]
#59에서 관련된 작업 추가하였어요!
